-- Strata Hyprland defaults.
--
-- Loaded by ~/.config/hypr/hyprland.lua. Do not edit this file: it belongs to
-- the image and is replaced on updates. Put your own settings in your own file,
-- after the line that loads this one — anything set there wins.
--
-- Hyprland 0.56 in Debian uses the Lua configuration format. The upstream
-- example lives at /usr/share/hypr/hyprland.lua and documents far more options
-- than are set here. Strata deliberately sets few: AGENTS.md asks for a minimal
-- usable default, not a theme.

------------------
---- PROGRAMS ----
------------------

-- Chosen in ADR-0009. foot renders on the CPU with no EGL dependency, which
-- keeps it working in QEMU and on broken drivers; fuzzel shares its rendering
-- stack. Hyprland's own example defaults to kitty and hyprlauncher, neither of
-- which Strata installs.
local terminal = "foot"
local menu     = "fuzzel"

local mainMod  = "SUPER"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- The shell. Reads /etc/xdg/quickshell/shell.qml unless the user has their
    -- own under ~/.config/quickshell/.
    hl.exec_cmd("quickshell")

    -- Notification daemon. The Debian binary is `mako`; the package is
    -- mako-notifier (the `mako` source package builds python3-mako instead).
    hl.exec_cmd("mako -c /etc/strata/theme/mako.conf")

    -- Privilege prompts (ADR-0009). Debian ships it in libexec, not bin.
    hl.exec_cmd("/usr/libexec/hyprpolkitagent")

    -- Idle and lock handling.
    hl.exec_cmd("hypridle")

    -- Says something once if part of the above did not come up. Silent
    -- otherwise. hypridle sat here dying instantly for weeks and nothing said
    -- so; `strata doctor` reported it to nobody.
    hl.exec_cmd("/usr/lib/strata/session-check")

    -- Clipboard history. On Wayland the clipboard is owned by the source
    -- client, so without this, copying and then closing an application loses
    -- the content.
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Qt applications, including Calamares, should use the Wayland platform plugin
-- rather than falling back to XCB through XWayland (ADR-0010).
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

-- Qt applications take their colours from GTK's settings.
--
-- qt6-gtk-platformtheme is already in the image, so this needs no package: with
-- it, Qt reads the same settings.ini that GTK does and a Qt window stops being
-- the one light rectangle on a dark desktop. Calamares is the one that matters
-- — it is the first Qt application anyone sees, and it ran unthemed until now.
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

-- Where the desktop looks for .desktop files, icons and MIME defaults.
--
-- Unset, the specification says this defaults to /usr/local/share:/usr/share,
-- and Flatpak's exports are in neither. The consequence is not subtle: an
-- application installed from Flathub is invisible to xdg-open, to xdg-settings,
-- and to the SUPER+D launcher — Brave installs successfully and then nothing on
-- the system can open it, including tools that only ever call xdg-open.
--
-- Flatpak ships /etc/profile.d/flatpak.sh to set this, but a Wayland session
-- started by greetd never sources profile.d, and the file does not exist at all
-- until something pulls flatpak in. The paths are listed here whether or not
-- they exist, which costs nothing and means installing a Flatpak application
-- works in the session that is already running.
-- Appended one at a time rather than built as a literal: a nil in the middle of
-- a table constructor leaves a hole, and table.concat over a table with a hole
-- is undefined.
local data_dirs = {}
local home = os.getenv("HOME")
if home and home ~= "" then
    data_dirs[#data_dirs + 1] = home .. "/.local/share/flatpak/exports/share"
end
data_dirs[#data_dirs + 1] = "/var/lib/flatpak/exports/share"
data_dirs[#data_dirs + 1] = "/usr/local/share"
data_dirs[#data_dirs + 1] = "/usr/share"
hl.env("XDG_DATA_DIRS", table.concat(data_dirs, ":"))

----------------
---- LOOK   ----
----------------

-- Window borders follow the active colour scheme, the same one the bar, the
-- launcher, notifications and the terminal use. `strata theme set <name>`
-- rewrites this file's source; nothing here needs editing to change colour.
-- The fallback keeps the session usable if the theme has not been applied yet.
local ok, strata_colors = pcall(dofile, "/etc/strata/theme/colors.lua")
if not ok or type(strata_colors) ~= "table" then
    strata_colors = { active = "rgba(7aa2f7ee)", inactive = "rgba(262c35aa)" }
end

hl.config({
    general = {
        gaps_in     = 4,
        gaps_out    = 8,
        border_size = 2,
        col = {
            active_border   = { colors = { strata_colors.active } },
            inactive_border = { colors = { strata_colors.inactive } },
        },
        resize_on_border = true,
        layout           = "dwindle",
    },
})

hl.config({
    decoration = {
        rounding = 4,
        blur = {
            enabled = false, -- costs GPU time for no functional gain
        },
        shadow = {
            enabled = false,
        },
    },
})

hl.config({
    animations = {
        enabled = false, -- AGENTS.md: avoid excessive theming and animations
    },
})

hl.config({
    misc = {
        -- Strata provides its own background later; until then a plain surface
        -- is more honest than Hyprland's mascot wallpaper.
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-----------------
---- INPUT   ----
-----------------

hl.config({
    input = {
        kb_layout      = "us",
        follow_mouse   = 1,
        sensitivity    = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

---------------------
---- KEYBINDINGS ----
---------------------
--
-- AGENTS.md requires exactly these capabilities: open a terminal, launch an
-- application, close a window, change focus, move windows, switch workspaces,
-- log out. The rest are the tools ADR-0009 selected, which would otherwise be
-- installed but unreachable.

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D",      hl.dsp.exec_cmd(menu))

-- The web browser. Strata installs none by default (ADR-0003), so on a fresh
-- system this opens a terminal explaining how to get one rather than silently
-- doing nothing — which is the whole reason the wrapper exists (ADR-0011).
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd("sh -c 'browser || " .. terminal .. " -H sh -c \"browser; read -n1\"'"))
hl.bind(mainMod .. " + Q",      hl.dsp.window.close())
hl.bind(mainMod .. " + F",      hl.dsp.window.float({ action = "toggle" }))

-- Two ways to fill the screen, because they are different things and both get
-- asked for. "maximized" takes the whole workspace and leaves the bar visible;
-- "fullscreen" covers everything, which is what a video or a game wants.
--
-- The two mode names are Hyprland's own: it rejects anything else with
-- "invalid mode (expected fullscreen/maximized)", which is how they were
-- established rather than guessed.
hl.bind(mainMod .. " + M",         hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

-- Log out of the session.
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

-- Lock the screen. SHIFT is needed because SUPER+L is the vim-style "focus
-- right" binding below.
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))

-- Screenshot a selected region to the clipboard (ADR-0009: grim + slurp;
-- hyprshot is not packaged in Debian).
--
-- stdin from /dev/null: slurp reads candidate boxes from stdin whenever stdin
-- is not a terminal, and waits for an EOF. Whether Hyprland hands a child a
-- pipe depends on how the session was started, so this does not depend on it.
-- The same trap is what made the bar's screenshot menu do nothing at all.
hl.bind("PRINT",           hl.dsp.exec_cmd("sh -c 'exec 0</dev/null; grim -g \"$(slurp)\" - | wl-copy'"))
hl.bind("SHIFT + PRINT",   hl.dsp.exec_cmd("sh -c 'grim - | wl-copy'"))

-- Clipboard history.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("sh -c 'cliphist list | fuzzel --dmenu | cliphist decode | wl-copy'"))

-- Focus, with both arrows and vim keys.
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + H",     hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "down" }))

-- Move the focused window.
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- Workspaces.
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Mouse.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and brightness keys.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
