-- Strata Hyprland defaults.
--
-- Loaded by ~/.config/hypr/hyprland.lua. Do not edit this file: it belongs to
-- the image and is replaced on updates. Put your own settings in your own file,
-- after the line that loads this one — anything set there wins.
--
-- Hyprland 0.56 in Debian uses the Lua configuration format. The upstream
-- example lives at /usr/share/hypr/hyprland.lua and documents far more options
-- than are set here. Strata deliberately sets few: AGENTS.md asks for a minimal
-- usable default, so what is set here is the Strata look (ADR-0012) and nothing
-- that changes how the compositor behaves.

------------------
---- PROGRAMS ----
------------------

-- Chosen in ADR-0009. foot renders on the CPU with no EGL dependency, which
-- keeps it working in QEMU and on broken drivers; fuzzel shares its rendering
-- stack. Hyprland's own example defaults to kitty and hyprlauncher, neither of
-- which Strata installs.
local terminal = "foot"
local menu     = "fuzzel"

local mainMod  = "SUPER"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- The shell. Reads /etc/xdg/quickshell/shell.qml unless the user has their
    -- own under ~/.config/quickshell/.
    hl.exec_cmd("quickshell")

    -- Notifications are served by the shell itself (ADR-0012). There is
    -- deliberately no mako here: two processes cannot both own
    -- org.freedesktop.Notifications, and whichever won the race would decide
    -- what the desktop looked like.

    -- The wallpaper. hyprpaper reads ~/.config/hypr/hyprpaper.conf when the
    -- user has one and Strata's otherwise, rather than relying on a fallback
    -- search path that would silently leave the desktop black if it changed.
    hl.exec_cmd("sh -c 'test -f \"$HOME\"/.config/hypr/hyprpaper.conf " ..
                "&& exec hyprpaper || exec hyprpaper -c /etc/hypr/hyprpaper.conf'")

    -- Privilege prompts (ADR-0009). Debian ships it in libexec, not bin.
    hl.exec_cmd("/usr/libexec/hyprpolkitagent")

    -- Idle and lock handling. Same reasoning as hyprpaper above: without a
    -- config hypridle starts, registers no listener, and does nothing at all.
    hl.exec_cmd("sh -c 'test -f \"$HOME\"/.config/hypr/hypridle.conf " ..
                "&& exec hypridle || exec hypridle -c /etc/hypr/hypridle.conf'")

    -- Clipboard history. On Wayland the clipboard is owned by the source
    -- client, so without this, copying and then closing an application loses
    -- the content.
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Qt applications, including Calamares, should use the Wayland platform plugin
-- rather than falling back to XCB through XWayland (ADR-0010).
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

----------------
---- LOOK   ----
----------------

-- The colours are Strata's, from /etc/xdg/quickshell/theme.js. Keeping the
-- window borders and the shell on one palette is the whole of the theme: the
-- accent marks what is focused, and nothing else is coloured.
hl.config({
    general = {
        gaps_in     = 5,
        gaps_out    = 10,
        border_size = 2,
        col = {
            -- accent, fading into the dimmed accent along the border
            active_border   = { colors = { "rgba(8fb6c9ee)", "rgba(3d515ccc)" } },
            inactive_border = { colors = { "rgba(212830aa)" } },
        },
        resize_on_border = true,
        layout           = "dwindle",
    },
})

hl.config({
    decoration = {
        -- Matches the shell's own corner radius.
        rounding = 8,
        blur = {
            enabled = false, -- costs GPU time for no functional gain
        },
        shadow = {
            enabled = false,
        },
        -- An unfocused window recedes very slightly. Cheap, and it makes a
        -- full-screen tiling layout readable at a glance.
        inactive_opacity = 0.97,
    },
})

-- AGENTS.md asks for no *excessive* animation, which is not the same as none:
-- without any, a window appears with no indication of where it came from, and
-- on a tiling layout that is genuinely disorienting.
--
-- Hyprland's own defaults are used rather than a hand-tuned curve. `bezier` and
-- `animation` are not ordinary keywords — they take positional argument lists —
-- and the exact Lua spelling of them cannot be checked against the packaged
-- Hyprland from this repository. A configuration error here costs the session,
-- and a session is worth more than a tuned easing curve. Tuning them is a
-- follow-up to be made with Hyprland in front of you.
hl.config({
    animations = {
        enabled = true,
    },
})

hl.config({
    misc = {
        -- hyprpaper puts Strata's own wallpaper up; Hyprland's mascot must not
        -- appear behind it in the moment before it does.
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-----------------
---- INPUT   ----
-----------------

hl.config({
    input = {
        kb_layout      = "us",
        follow_mouse   = 1,
        sensitivity    = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

---------------------
---- KEYBINDINGS ----
---------------------
--
-- AGENTS.md requires exactly these capabilities: open a terminal, launch an
-- application, close a window, change focus, move windows, switch workspaces,
-- log out. The rest are the tools ADR-0009 selected, which would otherwise be
-- installed but unreachable.

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + D",      hl.dsp.exec_cmd(menu))

-- The web browser. Strata installs none by default (ADR-0003), so on a fresh
-- system this opens a terminal explaining how to get one rather than silently
-- doing nothing — which is the whole reason the wrapper exists (ADR-0011).
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd("sh -c 'browser || " .. terminal .. " -H sh -c \"browser; read -n1\"'"))
hl.bind(mainMod .. " + Q",      hl.dsp.window.close())
hl.bind(mainMod .. " + F",      hl.dsp.window.float({ action = "toggle" }))

-- Log out of the session.
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

-- Lock the screen. SHIFT is needed because SUPER+L is the vim-style "focus
-- right" binding below. The helper picks the right configuration and refuses to
-- stack a second hyprlock on top of a running one.
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("/usr/lib/strata/lock"))

-- Screenshot a selected region to the clipboard (ADR-0009: grim + slurp;
-- hyprshot is not packaged in Debian).
hl.bind("PRINT",           hl.dsp.exec_cmd("sh -c 'grim -g \"$(slurp)\" - | wl-copy'"))
hl.bind("SHIFT + PRINT",   hl.dsp.exec_cmd("sh -c 'grim - | wl-copy'"))

-- Clipboard history.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("sh -c 'cliphist list | fuzzel --dmenu | cliphist decode | wl-copy'"))

-- Focus, with both arrows and vim keys.
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + H",     hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "down" }))

-- Move the focused window.
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- Workspaces.
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Mouse.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and brightness keys.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })

-- Display brightness. brightnessctl ships the udev rule that makes this work
-- without privileges; the shell reads the same device back and shows the OSD.
-- Never all the way to zero: `5%-` stops at 1%, so the screen cannot be turned
-- off by holding a key.
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -q -c backlight set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -q -c backlight set 5%-"), { locked = true, repeating = true })
